version: "3.4"
services:
  db:
    container_name: mongodb
    image: mongo:4.2.0-bionic
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    networks:
      - ginapi

  api:
    container_name: gin_tutorial
    build: .
    ports:
      - 8080:8080
    networks:
      - ginapi
    depends_on:
      - db
    environment:
      DBHOST: "mongodb://db"
      SECRETORKEY: "secretOrKey"

networks:
  ginapi:
